openapi: 3.0.3
info:
  title: Backend API boiler plate
  description: Backend API boiler plate
  termsOfService: http://swagger.io/terms/
  contact:
    email: quentin.danneville@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: http:localhost:4000/api/v1/
 
tags:
  - name: Typescript + Express APIs
    description: typescript + express APIs
 
paths:
  /:
    get:
      description: Returns 'Hello world !' to the caller
      tags: 
        - greeting
      operationId: Hello
      parameters:
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
 
components:
  schemas:
    HelloResponse:
      type: object
      additionalProperties: false
      required:
        - message
      properties:
        message:
          type: string